# Generated by Django 5.0 on 2023-12-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_order_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("NW", "New"),
                    ("HD", "Held"),
                    ("PK", "Parked"),
                    ("TP", "To Process"),
                    ("FD", "Future End Date"),
                    ("AW", "Awaiting Stock"),
                    ("IS", "Issues"),
                    ("CN", "Connected"),
                ],
                default="NW",
                max_length=2,
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["order_created"], name="api_order_order_c_823ea9_idx"
            ),
        ),
    ]
