# Generated by Django 5.0 on 2023-12-27 19:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_rename_name_company_company_name_order_order_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="company_Monthly_spend",
            new_name="company_Monthly_Spend",
        ),
        migrations.RenameField(
            model_name="company",
            old_name="company_Number_of_orders",
            new_name="company_Number_Of_Orders",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="order_Delivery_city",
            new_name="order_Delivery_City",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="order_Delivery_county",
            new_name="order_Delivery_County",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="order_Delivery_house_number",
            new_name="order_Delivery_House_Number",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="order_Delivery_post_code",
            new_name="order_Delivery_Postcode",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="order_Delivery_street",
            new_name="order_Delivery_Street",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="order_First_name",
            new_name="order_First_Name",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="order_House_number",
            new_name="order_House_Number",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="order_Last_name",
            new_name="order_Last_Name",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="order_Post_code",
            new_name="order_Postcode",
        ),
    ]
