# Generated by Django 5.0 on 2023-12-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0022_alter_order_options_alter_order_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_Open",
            field=models.BooleanField(),
        ),
    ]
