# Generated by Django 5.0 on 2023-12-31 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0026_remove_order_search_vector"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_account_address",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="order",
            name="order_account_holder_mobile_number",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="order_additional_details",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="order",
            name="order_box_value",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="order_campaign",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="order_commission_details",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="order",
            name="order_connected_date",
            field=models.DateField(default="1970-01-01"),
        ),
        migrations.AddField(
            model_name="order",
            name="order_connection_type",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="order_contact_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="order_contact_title",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="order_date_of_birth",
            field=models.DateField(default="1970-01-01"),
        ),
        migrations.AddField(
            model_name="order",
            name="order_deal_source",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="order_eligibility_date",
            field=models.DateField(default="1970-01-01"),
        ),
        migrations.AddField(
            model_name="order",
            name="order_email_address",
            field=models.EmailField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="order_handset",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="order_loss_reason",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="order_mobile_number",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="order_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="order_network",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="order_network_account_number",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="order_sim_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="order_spend_cap",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="order_tariff",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="order_tariff_code",
            field=models.CharField(default="", max_length=255),
        ),
    ]
