# Generated by Django 5.0 on 2023-12-31 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0027_order_order_account_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_comapny_type",
            field=models.CharField(
                choices=[
                    ("SOT", "Sole Trader"),
                    ("LTD", "Limited Company"),
                    ("LTP", "Limited Partnership"),
                    ("PAR", "Partnership"),
                    ("LLP", "Limited liability Partnership"),
                    ("CHA", "Charity"),
                ],
                default="",
                max_length=3,
            ),
        ),
    ]
