# Generated by Django 5.0 on 2023-12-31 22:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0029_alter_order_company"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="order_comapny_type",
            new_name="order_company_type",
        ),
    ]
