# Generated by Django 5.0 on 2023-12-31 23:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0031_alter_order_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_City",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_County",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_Delivery_City",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_Delivery_County",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_Delivery_House_Number",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_Delivery_Postcode",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_Delivery_Street",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_Email",
            field=models.EmailField(blank=True, default="", max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_First_Name",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_House_Number",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_Landline",
            field=models.CharField(blank=True, default="", max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_Last_Name",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_Mobile",
            field=models.CharField(blank=True, default="", max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_Postcode",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_Street",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_Title",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_account_address",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_account_holder_mobile_number",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_additional_details",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_box_value",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_campaign",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_commission_details",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_company_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SOT", "Sole Trader"),
                    ("LTD", "Limited Company"),
                    ("LTP", "Limited Partnership"),
                    ("PAR", "Partnership"),
                    ("LLP", "Limited liability Partnership"),
                    ("CHA", "Charity"),
                ],
                default="",
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_connected_date",
            field=models.DateField(blank=True, default="1970-01-01", null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_connection_type",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_contact_name",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_contact_title",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_date_of_birth",
            field=models.DateField(blank=True, default="1970-01-01", null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_deal_source",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_eligibility_date",
            field=models.DateField(blank=True, default="1970-01-01", null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_email_address",
            field=models.EmailField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_handset",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_loss_reason",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_mobile_number",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_name",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_network",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_network_account_number",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_spend_cap",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_tariff",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_tariff_code",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
