# Generated by Django 5.0 on 2024-01-01 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0032_alter_order_order_city_alter_order_order_county_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_Open",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_Title",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mr", "Mr"),
                    ("mrs", "Mrs"),
                    ("ms", "Ms"),
                    ("miss", "Miss"),
                    ("dr", "Dr"),
                    ("prof", "Professor"),
                    ("sir", "Sir"),
                    ("madam", "Madam"),
                    ("rev", "Reverend"),
                ],
                default="",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_company_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SOT", "Sole Trader"),
                    ("LTD", "Limited Company"),
                    ("LTP", "Limited Partnership"),
                    ("PAR", "Partnership"),
                    ("LLP", "Limited liability Partnership"),
                    ("CHA", "Charity"),
                ],
                default="",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
