# Generated by Django 5.0 on 2024-01-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0033_alter_order_order_open_alter_order_order_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="order_contact_name",
        ),
        migrations.RemoveField(
            model_name="order",
            name="order_contact_title",
        ),
        migrations.AlterField(
            model_name="order",
            name="order_spend_cap",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
