# Generated by Django 5.0 on 2024-01-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0041_alter_order_order_sim_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_Title",
            field=models.CharField(
                choices=[
                    ("mr", "Mr"),
                    ("mrs", "Mrs"),
                    ("ms", "Ms"),
                    ("miss", "Miss"),
                    ("dr", "Dr"),
                    ("prof", "Professor"),
                    ("sir", "Sir"),
                    ("madam", "Madam"),
                    ("rev", "Reverend"),
                ],
                default="",
                max_length=20,
                null=True,
            ),
        ),
    ]
