# Generated by Django 5.0 on 2024-01-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0043_alter_order_order_company_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_company_name",
            field=models.CharField(default="", null=True),
        ),
    ]
