# Generated by Django 5.0 on 2024-01-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0048_alter_order_order_box_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_box_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
