# Generated by Django 5.0 on 2024-01-13 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0049_alter_order_order_box_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_First_Name",
            field=models.CharField(
                default="", help_text="Enter First Name", max_length=100, null=True
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="api.order",
                    ),
                ),
            ],
        ),
    ]
