# Generated by Django 5.0 on 2024-01-16 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0055_alter_comment_options_comment_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_campaign",
            field=models.CharField(
                choices=[
                    ("sprint", "Sprint"),
                    ("plan", "Chadwell Plan"),
                    ("hosted", "Chadwell Hosted"),
                    ("renewals", "Renewals"),
                ],
                default="",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
