# Generated by Django 5.0 on 2024-01-18 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0056_alter_order_order_campaign_alter_order_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("sprint", "Sprint"),
                            ("plan", "Chadwell Plan"),
                            ("hosted", "Chadwell Hosted"),
                            ("renewals", "Renewals"),
                        ],
                        default="",
                        null=True,
                    ),
                ),
                ("target", models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="order",
            name="order_campaign",
        ),
        migrations.AddField(
            model_name="order",
            name="campaign",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales",
                to="api.campaign",
            ),
        ),
    ]
