# Generated by Django 5.0 on 2024-01-18 00:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0057_campaign_remove_order_order_campaign_order_campaign"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="name",
            field=models.CharField(default="", null=True),
        ),
    ]
