# Generated by Django 5.0 on 2024-01-18 13:44

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0058_alter_campaign_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalOrder",
            fields=[
                ("order_Id", models.IntegerField(blank=True, db_index=True)),
                (
                    "order_Number",
                    models.CharField(
                        db_index=True, default="", editable=False, max_length=255
                    ),
                ),
                ("order_Created", models.DateTimeField(blank=True, editable=False)),
                ("order_Updated", models.DateTimeField(blank=True, editable=False)),
                (
                    "order_Title",
                    models.CharField(
                        choices=[
                            ("mr", "Mr"),
                            ("mrs", "Mrs"),
                            ("ms", "Ms"),
                            ("miss", "Miss"),
                            ("dr", "Dr"),
                            ("prof", "Professor"),
                            ("sir", "Sir"),
                            ("madam", "Madam"),
                            ("rev", "Reverend"),
                        ],
                        default="",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "order_First_Name",
                    models.CharField(default="", max_length=100, null=True),
                ),
                (
                    "order_Last_Name",
                    models.CharField(default="", max_length=100, null=True),
                ),
                (
                    "order_Mobile",
                    models.CharField(default="", max_length=11, null=True),
                ),
                (
                    "order_Landline",
                    models.CharField(blank=True, default="", max_length=11, null=True),
                ),
                (
                    "order_Email",
                    models.EmailField(default="", max_length=254, null=True),
                ),
                (
                    "order_House_Number",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "order_Street",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "order_City",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "order_County",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "order_Postcode",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "order_Delivery_House_Number",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "order_Delivery_Street",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "order_Delivery_City",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "order_Delivery_County",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "order_Delivery_Postcode",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NW", "New"),
                            ("HD", "Held"),
                            ("PK", "Parked"),
                            ("TP", "To Process"),
                            ("FD", "Future End Date"),
                            ("AW", "Awaiting Stock"),
                            ("IS", "Issues"),
                            ("CN", "Connected"),
                            ("CNL", "Cancelled"),
                        ],
                        default="NW",
                        max_length=5,
                    ),
                ),
                (
                    "order_box_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "order_deal_source",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "order_connected_date",
                    models.DateField(blank=True, default="1970-01-01", null=True),
                ),
                (
                    "order_loss_reason",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "order_date_of_birth",
                    models.DateField(blank=True, default="1970-01-01", null=True),
                ),
                (
                    "order_account_address",
                    models.TextField(blank=True, default="", null=True),
                ),
                (
                    "order_network",
                    models.CharField(
                        choices=[("O2", "O2"), ("EE", "EE"), ("THREE", "Three")],
                        default="",
                        null=True,
                    ),
                ),
                (
                    "order_connection_type",
                    models.CharField(default="", max_length=255, null=True),
                ),
                (
                    "order_eligibility_date",
                    models.DateField(blank=True, default="1970-01-01", null=True),
                ),
                (
                    "order_handset",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "order_tariff",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "order_sim_required",
                    models.CharField(
                        choices=[("Y", "Yes"), ("N", "No")],
                        default="Y",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "order_tariff_code",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "order_spend_cap",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, null=True
                    ),
                ),
                (
                    "order_network_account_number",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "order_additional_details",
                    models.TextField(blank=True, default="", null=True),
                ),
                (
                    "order_commission_details",
                    models.TextField(blank=True, default="", null=True),
                ),
                ("order_Open", models.BooleanField(default=True)),
                (
                    "order_company_type",
                    models.CharField(
                        choices=[
                            ("SOT", "Sole Trader"),
                            ("LTD", "Limited Company"),
                            ("LTP", "Limited Partnership"),
                            ("PAR", "Partnership"),
                            ("LLP", "Limited liability Partnership"),
                            ("CHA", "Charity"),
                        ],
                        default="",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("order_company_name", models.CharField(default="", null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.campaign",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.company",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical order",
                "verbose_name_plural": "historical orders",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
