# Generated by Django 5.1.6 on 2025-02-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('inprogress', 'In Progress')], default='', null=True),
        ),
    ]
