# Generated by Django 5.1.6 on 2025-02-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_alter_comment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='order_Created',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_Created',
            field=models.DateTimeField(editable=False),
        ),
    ]
