# Generated by Django 5.1.6 on 2025-02-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_alter_historicalorder_order_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='order_Updated',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_Updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
