# Generated by Django 5.1.6 on 2025-02-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_alter_historicalorder_order_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='order_connected_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_connected_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
