# Generated by Django 5.1.6 on 2025-05-02 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_alter_historicalorder_order_connected_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('U', 'Urgent')], default='M', max_length=1)),
                ('status', models.CharField(choices=[('TD', 'To Do'), ('IP', 'In Progress'), ('C', 'Completed'), ('CN', 'Cancelled')], default='TD', max_length=2)),
                ('title', models.CharField(max_length=200)),
                ('due_date', models.DateTimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('reminder_date', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.order')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-due_date'],
                'indexes': [models.Index(fields=['due_date'], name='api_task_due_dat_54ead5_idx'), models.Index(fields=['status'], name='api_task_status_2aef03_idx'), models.Index(fields=['priority'], name='api_task_priorit_175238_idx'), models.Index(fields=['owner'], name='api_task_owner_i_3cb024_idx')],
            },
        ),
    ]
