# Generated by Django 5.0 on 2023-12-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_rename_customer_company_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="company",
            name="email",
        ),
        migrations.RemoveField(
            model_name="company",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="company",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="company",
            name="mobile",
        ),
        migrations.RemoveField(
            model_name="company",
            name="title",
        ),
        migrations.AddField(
            model_name="company",
            name="company_employees",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="company",
            name="company_monthly_spend",
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name="company",
            name="company_number_of_orders",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="company",
            name="company_type",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="company",
            name="company_updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="company",
            name="compapy_created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="order",
            name="order_city",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="order_county",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="order_delivery_city",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="order_delivery_county",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="order_delivery_house_number",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="order_delivery_post_code",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="order_delivery_street",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="order_email",
            field=models.EmailField(default="", max_length=254),
        ),
        migrations.AddField(
            model_name="order",
            name="order_first_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="order_house_number",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="order_landline",
            field=models.CharField(default="", max_length=11),
        ),
        migrations.AddField(
            model_name="order",
            name="order_last_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="order_mobile",
            field=models.CharField(default="", max_length=11),
        ),
        migrations.AddField(
            model_name="order",
            name="order_post_code",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="order_street",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="order_title",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(editable=False, max_length=15, unique=True),
        ),
    ]
