# Generated by Django 5.0 on 2023-12-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_remove_company_created_at_remove_company_email_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-order_created"]},
        ),
        migrations.RenameField(
            model_name="company",
            old_name="company_updated_at",
            new_name="company_updated",
        ),
        migrations.RenameField(
            model_name="company",
            old_name="compapy_created_at",
            new_name="compapy_created",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="order_created_at",
            new_name="order_created",
        ),
        migrations.AddField(
            model_name="order",
            name="order_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
