# Generated by Django 5.0 on 2023-12-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_alter_company_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="name",
            new_name="company_Name",
        ),
        migrations.AddField(
            model_name="order",
            name="order_Name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
