# Generated by Django 5.0 on 2023-12-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_remove_order_order_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_Number",
            field=models.CharField(default="", max_length=255, unique=True),
        ),
    ]
