# Generated by Django 5.0 on 2023-12-27 22:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0019_alter_company_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_Open",
            field=models.BooleanField(default=True),
        ),
    ]
