# Generated by Django 5.0 on 2023-12-31 08:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0025_order_search_vector"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="search_vector",
        ),
    ]
