# Generated by Django 5.0 on 2023-12-31 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0028_order_order_comapny_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="api.company",
            ),
        ),
    ]
