# Generated by Django 5.0 on 2024-01-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0034_remove_order_order_contact_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="order_account_holder_mobile_number",
        ),
        migrations.RemoveField(
            model_name="order",
            name="order_mobile_number",
        ),
        migrations.AlterField(
            model_name="order",
            name="order_name",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
