# Generated by Django 5.0 on 2024-01-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0037_alter_order_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="order_email_address",
        ),
        migrations.AlterField(
            model_name="order",
            name="order_sim_required",
            field=models.CharField(
                blank=True,
                choices=[("Y", "Yes"), ("N", "No")],
                default="Y",
                max_length=255,
                null=True,
            ),
        ),
    ]
