# Generated by Django 5.0 on 2024-01-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0039_alter_order_order_sim_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_sim_required",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")], default="Y", max_length=255
            ),
        ),
    ]
