# Generated by Django 5.0 on 2024-01-10 00:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0047_alter_order_order_box_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_box_value",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_network",
            field=models.CharField(
                choices=[("O2", "O2"), ("EE", "EE"), ("THREE", "Three")],
                default="",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_spend_cap",
            field=models.FloatField(default=0, null=True),
        ),
    ]
