# Generated by Django 5.0 on 2024-01-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0052_alter_comment_options_comment_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("NW", "New"),
                    ("HD", "Held"),
                    ("PK", "Parked"),
                    ("TP", "To Process"),
                    ("FD", "Future End Date"),
                    ("AW", "Awaiting Stock"),
                    ("IS", "Issues"),
                    ("CN", "Connected"),
                    ("CNL", "Cancelled"),
                ],
                default="NW",
                max_length=5,
            ),
        ),
    ]
