# Generated by Django 5.0 on 2024-01-14 00:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0054_alter_order_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created"]},
        ),
        migrations.AddField(
            model_name="comment",
            name="status",
            field=models.CharField(
                choices=[("open", "Open"), ("closed", "Closed")], default="", null=True
            ),
        ),
    ]
